# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Panrita.dev"
weight = 1

[id]
languageName = "Bahasa Indonesia"
languagedirection = "ltr"
title = "Panrita.dev"
weight = 1
